version: '2'
services:
  jenkins:
    image: jenkinsci/blueocean:latest
    command:
      - --loglevel warning
    volumes:
      - /opt/data/jenkins:/var/jenkins_home:Z
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
